<?php
namespace ajaxModal;


use yii\base\Widget;

class AjaxModal extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function begin($config = [])
    {
        return parent::begin($config); // TODO: Change the autogenerated stub
    }

    public static function end()
    {
        return parent::end(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}